### ISSUE TITLE
fd.read() - UnicodeDecodeError: 'charmap' codec can't decode byte 0x90

### ISSUE THREAD

**Issue by ballle98** [ballle98/amazon-statement-gen#6]
```
c:\git\amazon-statement-gen>asgen.py "C:\Users\lee_ballard\Downloads\15-Jun-2019_to_05-Sep-2019 (2).csv"
Traceback (most recent call last):
  File "C:\git\amazon-statement-gen\asgen.py", line 116, in <module>
    sys.exit(main())
  File "C:\git\amazon-statement-gen\asgen.py", line 51, in main
    fileBuff = fd.read()
  File "C:\Users\lee_ballard\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 11675: character maps to <undefined>

```

**Comment by ballle98** [comment]
https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character
